### ISSUE TITLE
Add a CONTRIBUTING.md with basic git commands

### ISSUE THREAD

**Issue by goelchahat** [kvaluruk/Data-Structures-And-Algorithms-Hacktoberfest18#120]

**Comment by AndreasElia** [comment]
"basic git commands" care to elaborate a little?

**Comment by kvaluruk** [comment]
The workflow (git commands) to be followed while contributing to the repository. 
For example
1. Fork repository on GitHub
2. Clone it onto your computer by `git clone https://github.com/{your username}/Data-Structures-And-Algorithms-Hacktoberfest18.git`

and so on...

**Comment by AndreasElia** [comment]
Ah gotcha, thanks!

**Comment by PritishSehzpaul** [comment]
1. @marcopollivier has formatted the CONTRIBUTING.md for easier readability.
2. Since this repo is aimed towards first time open source contributors (like me), some of whom might have little knowledge of git, I think we should also add the step to pull changes from parent repo **(kvaluruk/Data-Structures-And-Algorithms-Hacktoberfest18)** to local before doing a push so that the branch from which changes will be pulled is not stale.
i.e. something like -
`git add foo.java`
`git commit -m "Commit message"`
`git fetch upstream`
`git checkout master`
`git merge upstream/master`
`git push`

**PS:** I prefer `git fetch` over `git pull` which can also be used but `git fetch` is better at explaining what is happening.

I would like to take up this task. Also, I will be building on top of changes done by @marcopollivier.
